name: 'AI PR Reviewer with RAG'
description: 'Automated code review using GPT-4 with RAG-enhanced context'
author: 'Geethakrishnan Balasubramanian'

branding:
  icon: 'check-circle'
  color: 'blue'

inputs:
  openai_api_key:
    description: 'OpenAI API key for GPT-4 access'
    required: true
  github_token:
    description: 'GitHub token for API access'
    required: true
    default: ${{ github.token }}
  openai_model:
    description: 'OpenAI model to use'
    required: false
    default: 'gpt-4-turbo-preview'

runs:
  using: 'docker'
  image: 'Dockerfile.action'
  env:
    OPENAI_API_KEY: ${{ inputs.openai_api_key }}
    GITHUB_TOKEN: ${{ inputs.github_token }}
    OPENAI_MODEL: ${{ inputs.openai_model }}
